/*
 * telemetry.h
 *
 *  Created on: Dec 2, 2021
 *      Author: mckoyj
 */

#ifndef INCLUDE_TASKS_TELEMETRY_H_
#define INCLUDE_TASKS_TELEMETRY_H_

#include "driverlib.h"

#define SPI_ADCS EUSCI_A1_BASE

// ADCS telemetry
typedef enum {
ADCS_SETPWM_TORQUEROD1 = 1,
ADCS_SETPWM_TORQUEROD2,
ADCS_SETPWM_TORQUEROD3,
ADCS_TURNON_TORQUEROD1,
ADCS_TURNON_TORQUEROD2,
ADCS_TURNON_TORQUEROD3,
ADCS_TURNOFF_TORQUEROD1,
ADCS_TURNOFF_TORQUEROD2,
ADCS_TURNOFF_TORQUEROD3,
ADCS_SETPOLARITY_TORQUEROD1,
ADCS_SETPOLARITY_TORQUEROD2,
ADCS_SETPOLARITY_TORQUEROD3,
ADCS_SETPWMCOUNTER,
ADCS_GETMEASUREMENT_SUNSENSOR,
ADCS_GETMEASUREMENT_GYRO1,
ADCS_GETMEASUREMENT_GYRO2,
ADCS_GETMEASUREMENT_MAGNETOMETER1,
ADCS_GETMEASUREMENT_MAGNETOMETER2,
} adcsCommands_t;


uint8_t tx_rx_adcs(uint8_t command);
void transmitADCS(uint8_t command);
uint8_t receiveADCS(void);

#endif /* INCLUDE_TASKS_TELEMETRY_H_ */
